version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5001
